#!/usr/bin/env python3
"""Generate a scalable convex QP in Matrix Market format.

The generated problem is

    min 0.5 ||x-target||^2
    s.t. sum(x) <= budget, x >= 0.

Q is diagonal and G is sparse. The problem is useful for checking the CLI,
Matrix Market loader, KKT sparsity statistics, and convergence plotting.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a NatIDQP benchmark.")
    parser.add_argument("dimension", type=int, help="Number of variables")
    parser.add_argument("output_directory", type=Path)
    parser.add_argument(
        "--budget-ratio",
        type=float,
        default=0.35,
        help="Budget divided by sum(target), in (0,1) (default: 0.35)",
    )
    return parser.parse_args()


def write_coordinate(
    file_name: Path,
    rows: int,
    columns: int,
    entries: list[tuple[int, int, float]],
    symmetry: str = "general",
) -> None:
    with file_name.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(f"%%MatrixMarket matrix coordinate real {symmetry}\n")
        stream.write("% Generated by generate_box_qp.py\n")
        stream.write(f"{rows} {columns} {len(entries)}\n")
        for row, column, value in entries:
            stream.write(f"{row} {column} {value:.17g}\n")


def write_vector(file_name: Path, values: list[float]) -> None:
    with file_name.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("%%MatrixMarket matrix array real general\n")
        stream.write("% Generated by generate_box_qp.py\n")
        stream.write(f"{len(values)} 1\n")
        for value in values:
            stream.write(f"{value:.17g}\n")


def main() -> None:
    args = parse_args()
    n = args.dimension
    if n < 2:
        raise SystemExit("dimension must be at least 2")
    if not 0.0 < args.budget_ratio < 1.0:
        raise SystemExit("--budget-ratio must be between 0 and 1")

    output = args.output_directory
    output.mkdir(parents=True, exist_ok=True)

    target = [0.5 + (index + 1) / n for index in range(n)]
    budget = args.budget_ratio * sum(target)

    q_entries = [(index + 1, index + 1, 1.0) for index in range(n)]
    c_values = [-value for value in target]

    # First row: sum(x) <= budget. Remaining rows: -x_i <= 0.
    g_entries = [(1, index + 1, 1.0) for index in range(n)]
    g_entries.extend((index + 2, index + 1, -1.0) for index in range(n))
    h_values = [budget] + [0.0] * n

    write_coordinate(output / "Q.mtx", n, n, q_entries, symmetry="symmetric")
    write_vector(output / "c.mtx", c_values)
    write_coordinate(output / "G.mtx", n + 1, n, g_entries)
    write_vector(output / "h.mtx", h_values)

    print(f"Generated n={n}, m={n + 1} problem in {output}")
    print(f"budget={budget:.10g}, sum(target)={sum(target):.10g}")


if __name__ == "__main__":
    main()
